name: 'Create PR'
description: 'Create a release branch and open a stable PR'
inputs:
  version:
    description: 'Publish version'
    required: true
  isPreRelease:
    description: 'Whether this is a pre-release'
    default: 'true'
  ref_name:
    description: 'Branch name'
    required: true
  arazzo:
    description: 'Is Arazzo'
    default: 'false'

runs:
  using: "composite"
  steps:
      - name: Config git
        shell: bash
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Add Arazzo git changes
        if: ${{ inputs.arazzo == 'true' }}
        shell: bash
        run: git add extensions/arazzo-visualizer/arazzo-designer-extension/package.json

      - name: Commit version
        shell: bash
        id: commit
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git diff --staged --quiet || git commit -m "Update version to ${{ inputs.version }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create tag
        shell: bash
        id: create_tag
        run: |
          git tag ${{ inputs.version }}
          git push origin "refs/tags/${{ inputs.version }}"

      - name: Create release branch
        shell: bash
        if: ${{ inputs.isPreRelease == 'false' }}
        id: create_branch
        run: |
          git checkout -b "${{ inputs.version }}"
          git push origin "refs/heads/${{ inputs.version }}"

      - name: Create Pull Request
        shell: bash
        if: ${{ inputs.isPreRelease == 'false' }}
        id: pr
        run: |
          baseBranch=""
          if [ "${{ inputs.arazzo }}" == 'true' ]; then
            baseBranch="stable/arazzo-visualizer"
          fi
          pr=$(gh pr create -B "$baseBranch" -H "${{ inputs.version }}" --title "Merge \"${{ inputs.version }}\" into \"$baseBranch\"" --body '$subject')
          echo "prURL=$pr" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
