name: Build Arazzo Visualizer

on:
  workflow_call:
    inputs:
      isPreRelease:
        type: boolean
        default: true
      runTrivy:
        type: boolean
        default: true
      arazzo:
        description: Build Arazzo extension
        type: boolean
        required: false
        default: true
      version:
        default: 'N/A'
        type: string
        required: false
      isReleaseBuild:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      isPreRelease:
        type: boolean
        required: true
        default: true
      runTrivy:
        type: boolean
        required: true
        default: true
      arazzo:
        description: Build Arazzo extension
        type: boolean
        required: true
        default: true
      version:
        type: choice
        description: 'Enter the version type'
        required: true
        default: 'N/A'
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'N/A'

jobs:
  build:
    name: Build VSIX
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      isPreRelease: ${{ inputs.isPreRelease }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Set up PNPM
        run: |
          corepack enable
          corepack prepare pnpm@10.11.0 --activate

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache-dependency-path: |
            arazzo-designer-cli/go.sum
            extensions/arazzo-visualizer/arazzo-designer-lsp/go.sum

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Update Arazzo visualizer version
        if: ${{ inputs.version != 'N/A' }}
        working-directory: extensions/arazzo-visualizer/arazzo-designer-extension
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Build Arazzo visualizer
        if: ${{ inputs.arazzo }}
        run: node common/scripts/install-run-rush.js build --to arazzo-visualizer

      - name: Upload VSIX
        if: ${{ inputs.arazzo }}
        uses: actions/upload-artifact@v4
        with:
          name: VSIX
          path: |
            arazzo-visualizer-*.vsix
            extensions/arazzo-visualizer/arazzo-designer-extension/vsix/*.vsix
          if-no-files-found: error

      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.runTrivy }}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: "1"
          timeout: 10m
          skip-dirs: common/temp
          ignore-unfixed: true
